#number port
server:
  port: 8091

spring:
#config H2 in memory
  h2:
    console:
      enabled: true
      path: "/h2-console"
#datasource
  datasource:
    url: "jdbc:h2:mem:dbrest"
    driver-class-name: "org.h2.Driver"
    username: sa
    password: sa

#config JPA
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: "org.hibernate.dialect.H2Dialect"
